version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - next_build:/app/.next
      - node_modules:/app/node_modules
    restart: always

volumes:
  next_build:
  node_modules: